---
- name: Download Dokuwikis source
  ansible.builtin.include_tasks: download.yml

- name: Run configuration specific tasks
  ansible.builtin.include_tasks: configure.yml
  when: dokuwiki_deploy_config

- name: Install and uninstall plugins
  ansible.builtin.include_tasks: plugins.yml
